namespace: k1s

###################################
## Example Service Configuration ##
###################################

example:
  name: example
  namespace: k1s
  replicas: 1

  service:
    type: ClusterIP

    ports:
      name: http
      port: 3060
  
  image: # set automatically in skaffold
  pullPolicy: IfNotPresent

  ingress:
    entrypoint: websecure
    rule: Host(`example-service.example.com`)
